name: compile webGL

on:
  push:
    branches:
      - main

jobs:
  webgl_job:
    name: compile webgl unity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
         # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - uses: game-ci/unity-builder@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: WebGL
      - uses: actions/upload-artifact@v2
        with:
          name: Build-WebGL
          path: ${{ github.workspace }}/build/WebGL/**/*
  
  server_job:
    name: compile server unix
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

         # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - uses: game-ci/unity-builder@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: StandaloneLinux64
          customParameters: -EnableHeadlessMode
          customImage: 'unityci/editor:windows-2020.3.31f1-base-0.17.2'
      - uses: actions/upload-artifact@v2
        with:
          name: Build-Linux-Server
          path: ${{ github.workspace }}/build/StandaloneLinux64/**/*
