name: compile webGL

on:
  push:
    branches:
      - main
      - feature/guxal/workflows

jobs:
  example_job:
    name: compile webgl unity
    runs-on: ubuntu-latest
    steps:
      - name: command
        run: ls
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: WebGL
          projectPath: Nuruk-Unity3D

